CREATE TABLE IF NOT EXISTS USERS
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     varchar(100) NOT NULL,
    login    varchar(100) NOT NULL,
    email    varchar(200) NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS MPAS
(
    mpa_id      INTEGER PRIMARY KEY,
    name        varchar(100) NOT NULL,
    description varchar(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(100) NOT NULL,
    description  varchar(200),
    duration     int,
    release_date date         NOT NULL,
    mpa_id       integer      NOT NULL,
    FOREIGN KEY (mpa_id) REFERENCES MPAS (mpa_id),
    CHECK (duration > 0)
);

CREATE TABLE IF NOT EXISTS GENRES
(
    genre_id INTEGER PRIMARY KEY,
    name     varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    genre_id INTEGER NOT NULL,
    film_id  INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES FILMS (id),
    FOREIGN KEY (genre_id) REFERENCES GENRES (genre_id)
);

CREATE TABLE IF NOT EXISTS LIKES
(
    user_id INTEGER NOT NULL,
    film_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES FILMS (id),
    FOREIGN KEY (user_id) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    user_id   INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    status    INTEGER NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CHECK (status) IN (0, 1), -- 1-APPROVED, 0-NOT APPROVED
    FOREIGN KEY (user_id) REFERENCES USERS (id),
    FOREIGN KEY (friend_id) REFERENCES USERS (id)
);